[package]
name = "cargo-prebuilt"
version = "0.6.0-dev"
edition = "2021"
authors = ["harmless-tech"]
description = "Download prebuilt crate binaries for many different platforms"
readme = "README.md"
license = "MIT"
#homepage = ""
repository = "https://github.com/cargo-prebuilt/cargo-prebuilt"
keywords = ["cargo", "cargo-subcommand", "binary"]
rust-version = "1.65"
include = [
    "keys/",
    "src/",
    "build.rs",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[dependencies]
base64 = { version = "0.21.2", optional = true }
bpaf = { version = "0.9.0", features = ["autocomplete", "batteries"] }
flate2 = "1.0.26"
hex = "0.4.3"
home = "0.5.5"
mimalloc = { version = "0.1.37", optional = true }
minisign = { version = "0.7.5", optional = true }
native-tls = { version = "0.2.11", optional = true }
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.99"
sha2 = { version = "0.10.7", optional = true }
sha3 = { version = "0.10.8", optional = true }
tar = "0.4.38"
thiserror = "1.0.40"
toml = { version = "0.7.5", default-features = false, features = ["parse"] }
ureq = { version = "2.7.1", default-features = false, features = ["gzip", "brotli"] }

[features]
default = ["native", "vendored-openssl", "default-no-tls"]
default-native = ["native", "default-no-tls"]
default-rustls = ["rustls", "default-no-tls"]
default-no-tls = ["indexes", "security", "color"]
indexes = ["github-public"]
github-public = []
github-private = [] # TODO: Under dev
#gitlab-public = [] #TODO: Under dev
#gitlab-private = [] #TODO: Under dev
#forgejo-public = [] #TODO: Under dev
#forgejo-private = [] #TODO: Under dev
#gitea-public = ["forgejo-public"] #TODO: Under dev
#gitea-private = ["forgejo-private"] #TODO: Under dev
#custom-http-public = [] #TODO: Under dev
#custom-http-private = [] #TODO: Under dev
security = ["sha2", "sha3", "sig"]
sha2 = ["dep:sha2"]
sha3 = ["dep:sha3"]
sig = ["dep:minisign", "dep:base64"]
rustls = ["ureq/tls"]
rustls-native-certs = ["rustls", "ureq/native-certs"]
native = ["native-tls", "ureq/native-tls"]
vendored-openssl = ["native", "ureq/native-tls", "native-tls/vendored"]
mimalloc = ["dep:mimalloc"]
color = ["bpaf/bright-color"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.quick-build]
inherits = "release"
opt-level = 0
lto = false
codegen-units = 16
panic = "abort"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[package.metadata.binstall.overrides.aarch64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
