[package]
name = "cargo-prebuilt"
version = "0.5.2"
edition = "2021"
authors = ["harmless-tech"]
description = "Download prebuilt crate binaries for many different platforms"
readme = "README.md"
license = "MIT"
#homepage = ""
repository = "https://github.com/cargo-prebuilt/cargo-prebuilt"
keywords = ["cargo", "cargo-subcommand", "binary"]
rust-version = "1.60"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

include = [
    "src/",
    "build.rs",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[dependencies]
bpaf = { version = "0.7.10", features = ["autocomplete", "batteries"] }
flate2 = "1.0.26"
hex = "0.4.3"
home = "0.5.4"
nanoserde = "0.1.32"
native-tls = "0.2.11"
owo-colors = { version = "3.5.0", features = ["supports-colors"] }
sha2 = "0.10.6"
tar = "0.4.38"
thiserror = "1.0.40"
ureq = { version = "2.6.2", default-features = false, features = ["gzip", "brotli", "native-tls", "native-certs"] }

[features]
default = ["vendored-openssl", "bright-color", "github-public"]
github-public = []
github-private = [] # TODO: Under dev
#gitlab-public = [] #TODO: Under dev
#gitlab-private = [] #TODO: Under dev
#forgejo-public = [] #TODO: Under dev
#forgejo-private = [] #TODO: Under dev
#gitea-public = ["forgejo-public"] #TODO: Under dev
#gitea-private = ["forgejo-private"] #TODO: Under dev
vendored-openssl = ["native-tls/vendored"]
bright-color = ["bpaf/bright-color"]
dull-color = ["bpaf/dull-color"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true

[profile.quick-build]
inherits = "release"
opt-level = 0
lto = false
codegen-units = 16

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[package.metadata.binstall.overrides.aarch64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[package.metadata.binstall.overrides.i686-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
