[package]
name = "cargo-prebuilt"
version = "0.2.1"
edition = "2021"
authors = ["harmless-tech"]
description = "Download prebuilt crate binaries for many different platforms"
readme = "README.md"
license = "MIT"
#homepage = ""
repository = "https://github.com/crow-rest/cargo-prebuilt"
keywords = ["cargo", "cargo-subcommand", "binary"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

exclude = [
    ".github/",
    "justfile",
    ".gitignore",
    "rustfmt.toml"
]

[dependencies]
flate2 = "1.0.24"
hex = "0.4.3"
native-tls = { version = "0.2.11", features = ["vendored"] }
sha2 = "0.10.6"
tar = "0.4.38"
ureq = { version = "2.5.0", default-features = false, features = ["gzip", "native-tls", "native-certs"] }

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
