[package]
name = "cargo-prebuilt"
version = "0.6.8"
edition = "2021"
authors = ["harmless-tech"]
description = "Download prebuilt crate binaries for many different platforms"
readme = "README.md"
license = "MIT"
#homepage = ""
repository = "https://github.com/cargo-prebuilt/cargo-prebuilt"
categories = ["development-tools", "development-tools::cargo-plugins"]
keywords = ["cargo", "cargo-subcommand", "binary"]
rust-version = "1.70"
include = [
  "keys/",
  "src/",
  "build.rs",
  "Cargo.lock",
  "Cargo.toml",
  "LICENSE",
  "README.md",
]

[dependencies]
bpaf = { version = "0.9.11", features = ["autocomplete", "batteries"] }
directories = "5.0.1"
flate2 = "1.0.28"
hex = "0.4.3"
home = "0.5.9"
indexmap = { version = "2.2.6", features = ["serde"] }
mimalloc = { version = "0.1.39", optional = true }
minisign-verify = { version = "0.2.1", optional = true }
native-tls = { version = "0.2.11", optional = true }
owo-colors = { version = "4.0.0", features = [
  "supports-colors",
], optional = true }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
sha2 = { version = "0.10.8", optional = true }
sha3 = { version = "0.10.8", optional = true }
tar = "0.4.40"
toml = { version = "0.8.12", default-features = false, features = [
  "display",
  "parse",
] }
ureq = { version = "2.9.6", default-features = false, features = [
  "json",
  "gzip",
  "brotli",
] }

[features]
default = ["vendored-openssl", "default-native"]
default-native = ["native", "default-no-tls"]
default-rustls = ["rustls", "default-no-tls"]
default-no-tls = ["indexes", "security", "color"]
indexes = ["github-public", "github-private"]
github-public = []
github-private = []
#gitlab-public = [] #TODO: Under dev
#gitlab-private = [] #TODO: Under dev
#forgejo-public = [] #TODO: Under dev
#forgejo-private = [] #TODO: Under dev
#gitea-public = ["forgejo-public"] #TODO: Under dev
#gitea-private = ["forgejo-private"] #TODO: Under dev
#custom-http-public = [] #TODO: Under dev
#custom-http-private = [] #TODO: Under dev
security = ["sha2", "sha3", "sig"]
sha2 = ["dep:sha2"]
sha3 = ["dep:sha3"]
sig = ["dep:minisign-verify"]
rustls = ["ureq/tls"]
rustls-native-certs = ["rustls", "ureq/native-certs"]
native = ["native-tls", "ureq/native-tls"]
vendored-openssl = ["native", "native-tls/vendored"]
mimalloc = ["dep:mimalloc"]
color = ["dep:owo-colors", "bpaf/bright-color"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
debug = false
strip = true
panic = "abort"

[profile.small]
inherits = "release"
opt-level = "s"

[profile.quick-build]
inherits = "release"
opt-level = 0
lto = false
codegen-units = 16

[profile.bloat]
inherits = "release"
debug = true
strip = false

[lints.clippy]
cargo = "deny"
correctness = "deny"
complexity = "deny"
nursery = "deny"
pedantic = "deny"
perf = "deny"
style = "deny"
suspicious = "deny"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[package.metadata.binstall.overrides.aarch64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
