[package]
name = "cargo-prebuilt"
version = "0.6.3-dev"
edition = "2021"
authors = ["harmless-tech"]
description = "Download prebuilt crate binaries for many different platforms"
readme = "README.md"
license = "MIT"
#homepage = ""
repository = "https://github.com/cargo-prebuilt/cargo-prebuilt"
keywords = ["cargo", "cargo-subcommand", "binary"]
rust-version = "1.66"
include = [
    "keys/",
    "src/",
    "build.rs",
    "Cargo.lock",
    "Cargo.toml",
    "LICENSE",
    "README.md"
]

[dependencies]
bpaf = { version = "0.9.5", features = ["autocomplete", "batteries"] }
directories = "5.0.1"
flate2 = "1.0.28"
hex = "0.4.3"
home = "0.5.5"
indexmap = { version = "2.0.2", features = ["serde"] }
mimalloc = { version = "0.1.39", optional = true }
minisign-verify = { version = "0.2.1", optional = true }
native-tls = { version = "0.2.11", optional = true }
owo-colors = { version = "3.5.0", optional = true }
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.107"
sha2 = { version = "0.10.8", optional = true }
sha3 = { version = "0.10.8", optional = true }
supports-color = { version = "2.1.0", optional = true }
tar = "0.4.40"
thiserror = "1.0.50"
toml = { version = "0.8.2", default-features = false, features = ["display", "parse"] }
ureq = { version = "2.8.0", default-features = false, features = ["gzip", "brotli"] }

[features]
default = ["vendored-openssl", "default-native"]
default-native = ["native", "default-no-tls"]
default-rustls = ["rustls", "default-no-tls"]
default-no-tls = ["indexes", "security", "color"]
indexes = ["github-public"]
github-public = []
github-private = [] # TODO: Under dev
#gitlab-public = [] #TODO: Under dev
#gitlab-private = [] #TODO: Under dev
#forgejo-public = [] #TODO: Under dev
#forgejo-private = [] #TODO: Under dev
#gitea-public = ["forgejo-public"] #TODO: Under dev
#gitea-private = ["forgejo-private"] #TODO: Under dev
#custom-http-public = [] #TODO: Under dev
#custom-http-private = [] #TODO: Under dev
security = ["sha2", "sha3", "sig"]
sha2 = ["dep:sha2"]
sha3 = ["dep:sha3"]
sig = ["dep:minisign-verify"]
rustls = ["ureq/tls"]
rustls-native-certs = ["rustls", "ureq/native-certs"]
native = ["native-tls", "ureq/native-tls"]
vendored-openssl = ["native", "native-tls/vendored"]
mimalloc = ["dep:mimalloc"]
color = ["dep:owo-colors", "dep:supports-color", "bpaf/bright-color"]

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
panic = "abort"

[profile.small]
inherits = "release"
opt-level = "s"

[profile.quick-build]
inherits = "release"
opt-level = 0
lto = false
codegen-units = 16

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.tar.gz"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "tgz"

[package.metadata.binstall.overrides.x86_64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"

[package.metadata.binstall.overrides.aarch64-pc-windows-msvc]
pkg-url = "{ repo }/releases/download/v{ version }/{ target }.zip"
bin-dir = "{ bin }{ binary-ext }"
pkg-fmt = "zip"
