[target.x86_64-unknown-freebsd]
pre-build = "FREEBSD_MIRROR=\"$(fetch_best_freebsd_mirror)\" install_freebsd_package memstat"

[target.i686-unknown-freebsd]
pre-build = "FREEBSD_MIRROR=\"$(fetch_best_freebsd_mirror)\" install_freebsd_package memstat"
