[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cargo-prebuilt/cross-openssl:x86_64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cargo-prebuilt/cross-openssl:x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cargo-prebuilt/cross-openssl:aarch64-unknown-linux-gnu"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cargo-prebuilt/cross-openssl:aarch64-unknown-linux-musl"

[target.x86_64-unknown-freebsd]
image = "ghcr.io/cargo-prebuilt/cross-openssl:x86_64-unknown-freebsd"

[target.x86_64-unknown-netbsd]
image = "ghcr.io/cargo-prebuilt/cross-openssl:x86_64-unknown-netbsd"

[target.x86_64-unknown-illumos]
image = "ghcr.io/cargo-prebuilt/cross-openssl:x86_64-unknown-illumos"

[target.riscv64gc-unknown-linux-gnu]
image = "ghcr.io/cargo-prebuilt/cross-openssl:riscv64gc-unknown-linux-gnu"

[target.powerpc64-unknown-linux-gnu]
image = "ghcr.io/cargo-prebuilt/cross-openssl:powerpc64-unknown-linux-gnu"

[target.powerpc64le-unknown-linux-gnu]
image = "ghcr.io/cargo-prebuilt/cross-openssl:powerpc64le-unknown-linux-gnu"

[target.s390x-unknown-linux-gnu]
image = "ghcr.io/cargo-prebuilt/cross-openssl:s390x-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/cargo-prebuilt/cross-openssl:armv7-unknown-linux-gnueabihf"

[target.armv7-unknown-linux-musleabihf]
image = "ghcr.io/cargo-prebuilt/cross-openssl:armv7-unknown-linux-musleabihf"
