[unstable]
build-std = ["std", "panic_abort", "core", "alloc"]
build-std-features = ["panic_immediate_abort"]
panic-abort-tests = true

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "link-arg=-lgcc"]

[build]
rustflags = ["--cfg=has_std"]
