---
name: Lint

on:
  push:
    branches: [main, releases/0.7]
    paths: ["**.md", "**.yml", "**.sh", "**.json"]
  pull_request:
    branches: [main, releases/0.7]
  workflow_dispatch:

permissions:
  contents: read
  packages: read
  statuses: write

defaults:
  run:
    shell: bash

jobs:
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check spelling
        uses: crate-ci/typos@master

  super-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_JSCPD: false
          VALIDATE_RUST_2015: false
          VALIDATE_RUST_2018: false
          VALIDATE_RUST_2021: false
          VALIDATE_RUST_CLIPPY: false
