name: Rust Release

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  bin-name: cargo-prebuilt

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    outputs:
      tag: ${{ github.ref_name }}
      name: ${{ github.ref_name }}
      prerelease: ${{ steps.regex-tag.outputs.match == '' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: KyoriPowered/action-regex-match@v4
        id: regex-tag
        with:
          text: ${{ github.ref }}
          regex: '^refs\/tags\/v\d+\.\d+\.\d+$'

  publish-crates-io:
    if: ${{ ! contains(github.ref, '-dev') }}
    runs-on: ubuntu-latest
    needs: [release, build-native, build-ink-cross]
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: stable
      - name: Publish
        run: cargo +${{steps.toolchain.outputs.name}} publish --verbose --locked --token "${CRATES_TOKEN}"
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

  publish-github-com:
    runs-on: ubuntu-latest
    needs: [release, build-native, build-ink-cross]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: actions/download-artifact@v5
      - name: Merge hashes
        run: |
          set -euxo pipefail
          echo -n "" > hashes.sha256
          for D in target-*; do
            if [ -d "${D}" ]; then
              echo "${D}"
              pushd "${D}"
              cat ./*.sha256 >> ../hashes.sha256
              popd
            fi
          done
      - name: Sign archives
        run: |
          set -euxo pipefail
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install minisign
          echo -n "$SIGNING_KEY" | base64 --decode > ~/.minisign_secret.key
          for D in target-*; do
            if [ -d "${D}" ]; then
              echo "${D}"
              pushd "${D}"

              for file in ./*.tar.gz ./*.zip; do
                if [ -f "$file" ]; then
                  minisign -S -s ~/.minisign_secret.key -m "$file"
                  minisign -V -p ../keys/cargo-prebuilt.pub -m "$file"
                fi
              done

              popd
            fi
          done
          rm -f ~/.minisign_secret.key
        env:
          SIGNING_KEY: ${{ secrets.MINISIGN_SIGNING_KEY }}
      - name: Create and push artifacts to release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.release.outputs.tag }}
          name: ${{ needs.release.outputs.name }}
          allowUpdates: true
          prerelease: ${{ needs.release.outputs.prerelease }}
          artifacts: "target-*/*.minisig,target-*/*.tar.gz,target-*/*.zip,hashes.sha256"
          body: ""

  build-native:
    strategy:
      fail-fast: false
      matrix:
        rust-version: [nightly]
        info:
          - os: macos-latest
            target: aarch64-apple-darwin
            archive_ext: .tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            archive_ext: .tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            archive_ext: .zip
            file_ext: .exe
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            archive_ext: .zip
            file_ext: .exe
    runs-on: ${{ matrix.info.os }}
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: cargo-prebuilt/cargo-prebuilt-action@v4
        with:
          pkgs: cargo-auditable,coreutils
      - uses: dtolnay/rust-toolchain@master
        id: toolchain
        with:
          toolchain: ${{ matrix.rust-version }}
          targets: ${{ matrix.info.target }}
          components: rust-src
      - name: Test
        if: ${{ matrix.info.target != 'aarch64-pc-windows-msvc' }}
        run: cargo +${{steps.toolchain.outputs.name}} test --verbose --workspace --release --locked --target ${{ matrix.info.target }}
      - name: Build
        run: cargo +${{steps.toolchain.outputs.name}} auditable build --verbose --workspace --release --locked --target ${{ matrix.info.target }}
      - name: Test Run
        if: ${{ matrix.info.target != 'aarch64-pc-windows-msvc' }}
        run: |
          target/${{ matrix.info.target }}/release/${{ env.bin-name }}${{ matrix.info.file_ext }} just
          just --version
      - name: Tar
        if: ${{ contains(matrix.info.os, 'macos') }}
        run: tar czvf ${{ matrix.info.target }}${{ matrix.info.archive_ext }} -C ./target/${{ matrix.info.target }}/release ${{ env.bin-name }}${{ matrix.info.file_ext }}
      - name: Zip
        if: ${{ contains(matrix.info.os, 'windows') }}
        run: |
          cd target/${{ matrix.info.target }}/release
          7z a -tzip ../../../${{ matrix.info.target }}${{ matrix.info.archive_ext }} ${{ env.bin-name }}${{ matrix.info.file_ext }}
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            ${{ matrix.info.target }}${{ matrix.info.archive_ext }}
            ./target/${{ matrix.info.target }}/release/${{ env.bin-name }}${{ matrix.info.file_ext }}
      - name: Hash
        run: coreutils sha256sum ${{ matrix.info.target }}${{ matrix.info.archive_ext }} > ${{ matrix.info.target }}.sha256
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: target-${{ matrix.info.target }}
          path: |
            ${{ matrix.info.target }}${{ matrix.info.archive_ext }}
            ${{ matrix.info.target }}.sha256

  build-ink-cross:
    strategy:
      matrix:
        rust-version: [nightly]
        info:
          - target: aarch64-unknown-linux-gnu
          - target: aarch64-unknown-linux-musl
          - target: armv7-unknown-linux-gnueabihf
          - target: armv7-unknown-linux-musleabihf
          - target: powerpc64le-unknown-linux-gnu
          - target: powerpc64-unknown-linux-gnu
          - target: riscv64gc-unknown-linux-gnu
          - target: riscv64gc-unknown-linux-musl
          - target: s390x-unknown-linux-gnu
          - target: x86_64-unknown-linux-gnu
          - target: x86_64-unknown-linux-musl
          - target: x86_64-unknown-freebsd
          - target: x86_64-unknown-netbsd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: cargo-prebuilt/cargo-prebuilt-action@v4
        with:
          pkgs: coreutils
      - name: Build with ink cross
        run: |
          docker run --rm \
          --userns host --user "$(id -u)":"$(id -g)" \
          -v ./:/project \
          ghcr.io/cargo-prebuilt/ink-cross:${{ matrix.rust-version }}-${{ matrix.info.target }} \
          auditable build --verbose --workspace --release --locked --target ${{ matrix.info.target }}
      - name: Tar
        run: tar czvf ${{ matrix.info.target }}.tar.gz -C ./target/${{ matrix.info.target }}/release ${{ env.bin-name }}
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: |
            ${{ matrix.info.target }}.tar.gz
            ./target/${{ matrix.info.target }}/release/${{ env.bin-name }}
      - name: Hash
        run: coreutils sha256sum ${{ matrix.info.target }}.tar.gz > ${{ matrix.info.target }}.sha256
      - name: Artifact
        uses: actions/upload-artifact@v4
        with:
          name: target-${{ matrix.info.target }}
          path: |
            ${{ matrix.info.target }}.tar.gz
            ${{ matrix.info.target }}.sha256
